import { FormattedMessage } from "react-intl";
import { NavItemType } from "types";

const pages: NavItemType = {
  id: "Learning",
  featureName: "Learning",
  title: <FormattedMessage id="Learning" />,
  icon: "/assets/logos/ASK Type 2.svg",
  type: "group",
  children: [
    {
      id: "Chapter-Analysis",
      subFeatureName: "Chapter Analysis ",
      title: <FormattedMessage id="Chapter Analysis" />,
      type: "item",
      icon: "/assets/logos/Chapter Wise Analysis Type 2.svg",
      url: "/learning/chapter-analysis",
      breadcrumbs: false,
    },
    {
      id: "Ask-Questions",
      subFeatureName: "Ask Questions ",
      title: <FormattedMessage id="Ask Questions" />,
      type: "item",
      icon: "/assets/logos/ASK Type 2.svg",
      url: "/learning/ask-question",
      breadcrumbs: false,
    },
    {
      id: "Get-Questions",
      subFeatureName: "Get Questions ",
      title: <FormattedMessage id="Get Questions" />,
      type: "item",
      icon: "/assets/logos/GET Question Type 2.svg",
      url: "/learning/get-question",
      breadcrumbs: false,
    },
    {
      id: "Quizzes",
      subFeatureName: "Get Questions ",
      title: <FormattedMessage id="Quizzes" />,
      type: "item",
      icon: "/assets/logos/Quizz Type 2.svg",
      url: "/learning/quiz",
      breadcrumbs: false,
    },
    {
      id: "Interactive-Learning",
      subFeatureName: "Interactive Learning",
      title: <FormattedMessage id="Interactive Learning" />,
      type: "item",
      icon: "/assets/logos/Interactive Learning Type 2.svg",
      url: "/learning/interactive-learning",
      breadcrumbs: true,
    },
    {
      id: "Revision-Notes",
      subFeatureName: "Revision Notes",
      title: <FormattedMessage id="Revision Notes" />,
      type: "item",
      icon: "/assets/logos/Revision Notes Type 2.svg",
      url: "/learning/revision-notes",
      breadcrumbs: true,
    },
    {
      id: "Q and A",
      subFeatureName: "Q&A ",
      title: <FormattedMessage id="Q and A" />,
      type: "item",
      icon: "/assets/logos/Q and A Type 2.svg",
      url: "/learning/question and answer",
      breadcrumbs: true,
    },
    {
      id: "Case Study with MCQs",
      subFeatureName: "Case Study with MCQ",
      title: <FormattedMessage id="Case Study with MCQs" />,
      type: "item",
      icon: "/assets/logos/ASK Type 2.svg",
      url: "/learning/revision-notes",
      breadcrumbs: true,
    },
    {
      id: "PY Question Papers",
      subFeatureName: "PY QPs ",
      title: <FormattedMessage id="PY Question Papers" />,
      type: "item",
      icon: "/assets/logos/Preivious Year Questions Type 2.svg",
      url: "/learning/py-question-papers",
      breadcrumbs: true,
    },
    {
      id: "Mock Exams",
      subFeatureName: "Mock Exams ",
      title: <FormattedMessage id="Mock Exams" />,
      type: "item",
      icon: "/assets/logos/Mock Exam Type 2.svg",
      url: "/learning/mock-exams",
      breadcrumbs: true,
    },
    {
      id: "Podcasts",
      subFeatureName: "Podcasts",
      title: <FormattedMessage id="Podcasts" />,
      type: "item",
      icon: "/assets/logos/Podcasts Type 2.svg",
      url: "/learning/Podcasts",
      breadcrumbs: true,
    },
  ],
};
export default pages;
